server:
  port: 8084
  servlet:
    context-path: /wx


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.47.184:3306/wx_test
    username: root
    password: root
  mvc:
    view:
      suffix: .html
      prefix: /

#mybatis:
mybatis-plus:
  global-config:
    db-config:
#      删除字段
      logic-delete-field: deleted
#      删除标志
      logic-delete-value: 1
#      未删除标志
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

